services:
  api:
    build: ./api
    container_name: orion_api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - postgres
    
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=banco_orion
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: