# Generated by Django 6.0.7 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('ultimo_nome', models.CharField(max_length=100, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
    ]
