# Generated by Django 6.0.8 on 2026-08-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_operacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=20, unique=True)),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança'), ('INVESTIMENTO', 'Investimento')], default='CORRENTE', max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('limite', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('BLOQUEADA', 'Bloqueada'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='api_operacoes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('QUITADO', 'Quitado')], default='PENDENTE', max_length=20)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='api_operacoes.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('ENERGIA', 'Energia'), ('AGUA', 'Água'), ('INTERNET', 'Internet'), ('SALARIO', 'Salário'), ('IMPOSTOS', 'Impostos')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api_operacoes.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to='api_operacoes.conta')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='api_operacoes.conta')),
            ],
        ),
    ]
