# Generated by Django 6.0 on 2026-08-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_operacoes', '0003_alter_cliente_email_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bilhete de Identidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='morada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Província'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rendimento_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Rendimento Mensal (Kz)'),
        ),
        migrations.AddField(
            model_name='conta',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='conta',
            name='moeda',
            field=models.CharField(blank=True, default='AOA', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='finalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='api_operacoes.cliente'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_conta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.CharField(blank=True, choices=[('ATIVA', 'Ativa'), ('BLOQUEADA', 'Bloqueada'), ('ENCERRADA', 'Encerrada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança'), ('INVESTIMENTO', 'Investimento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='api_operacoes.conta'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('QUITADO', 'Quitado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='taxa_juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ENERGIA', 'Energia'), ('AGUA', 'Água'), ('INTERNET', 'Internet'), ('SALARIO', 'Salário'), ('IMPOSTOS', 'Impostos'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('TRANSPORTE', 'Transporte'), ('COMERCIO', 'Comércio'), ('OUTROS', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api_operacoes.conta'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to='api_operacoes.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='api_operacoes.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
